codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:
        paths: "tests/"
        target: 100%
      source:
        paths: "jupytext/"
        target: 97%
        threshold': .2%
    patch: off  # disable codecov/patch
